[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "v0.15.1"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.18.18"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/openfaas/faas-cli"
  version = "0.12.9"
